# Generated by Django 4.2.7 on 2023-12-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contacts_product_item_avalable_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='item_avalable',
            new_name='item_available',
        ),
    ]
