# Generated by Django 4.2.6 on 2023-11-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customer_delete_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
