# Generated by Django 4.2.6 on 2023-11-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_product_product_avalable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_avalable',
            new_name='item_avalable',
        ),
    ]
