# Generated by Django 4.2.7 on 2023-12-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_category_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='item_avalable',
            new_name='product_available',
        ),
    ]
